from __future__ import annotations

import os

USE_SPARSE_JACOBIAN_DEFAULT = True
WEGSCHEIDER_CYCLICITY_ENABLED_DEFAULT = True
LIMIT_BLAS_THREADS_PER_WORKER_DEFAULT = True
MAX_PARALLEL_BATCH_WORKERS_DEFAULT = max(1, (os.cpu_count() or 1) - 1)
RESULT_CACHE_CAP_DEFAULT = 1000
PREVIEW_CACHE_CAP_DEFAULT = 1000

__all__ = [
    "USE_SPARSE_JACOBIAN_DEFAULT",
    "WEGSCHEIDER_CYCLICITY_ENABLED_DEFAULT",
    "LIMIT_BLAS_THREADS_PER_WORKER_DEFAULT",
    "MAX_PARALLEL_BATCH_WORKERS_DEFAULT",
    "RESULT_CACHE_CAP_DEFAULT",
    "PREVIEW_CACHE_CAP_DEFAULT",
]
