"""Shared constants for the fitting UI subsystem."""

INITIAL_PREFIX = "init:"
FITTING_DEFAULT_SOLVER = "BDF"
FITTING_SOLVERS = ("Radau", "BDF")
FITTING_METHODS = ("lm", "trf", "dogbox", "differential_evolution")
FITTING_MAX_NFEV_RANGE = (10, 10_000)
FITTING_SEED_RANGE = (0, 999_999)
FITTING_SCIENTIFIC_VALUE_MAX = 1e300
DEFAULT_PARALLEL_STARTS = 4
_SAMPLING_ALL_POINTS_SENTINEL = 0
